- name: Ajout de la database Prometheus
  uri:
    url: "http://{{ groups['grafana'][0] }}:3000/api/datasources"
    method: POST
    user: "administrateur"
    password: "R00tR00t"
    force_basic_auth: true
    headers:
      Content-Type: "application/json"
    body: 
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://{{ groups['prometheus'][0] }}:9090",
        "access": "proxy",
        "isDefault": true
      }
    body_format: json
    status_code: 200
    validate_certs: false


