global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - "172.20.0.2:3000"  # Grafana
          - "172.20.0.4:9093"  # AlertManager

  - job_name: 'machines'
    static_configs:
      - targets:
          - "10.0.2.15:9100" #hote

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "172.20.0.4:9093" #alertmanager
