---
- name: Copier prometheus.yml dans  Prometheus
  command: docker cp "{{ role_path }}/files/prometheus.yml" prometheus:/etc/prometheus/prometheus.yml

- name: Redémarrage du conteneur Prometheus
  docker_container:
    name: prometheus
    state: started
    restart: yes

- name: Déploiement du fichier  pour Prometheus
  include_tasks: config.yml
