---
- name: Création d'un réseau Docker
  hosts: localhost
  become: true
  tasks:
    - name: Vérification que Docker est en cours d'exécution
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Création d'un réseau Docker
      community.docker.docker_network:
        name: sae502
        driver: bridge
        ipam_config:
          - subnet: 172.20.0.0/24
        state: present
